[package]
name = "caesar-core-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
caesar-core = { path = "../caesar-core" }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
serde.workspace = true
serde_json.workspace = true
zeroize.workspace = true
